In [1]:
print("Hello AK")

Hello AK


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()
import streamlit as st
from streamlit_option_menu import option_menu
import warnings
warnings.filterwarnings("ignore")

In [17]:
df_train = pd.read_csv(r"C:\Users\HP\Downloads\Train_Dataset.csv.zip")

df_train

ID Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  \
0       12142509          6750        0.0         0.0          1.0        0.0   
1       12138936         20250        1.0         0.0          1.0        NaN   
2       12181264         18000        0.0         0.0          1.0        0.0   
3       12188929         15750        0.0         0.0          1.0        1.0   
4       12133385         33750        1.0         0.0          1.0        0.0   
...          ...           ...        ...         ...          ...        ...   
121851  12207714         29250        0.0         0.0          NaN        1.0   
121852  12173765         15750        0.0         1.0          1.0        0.0   
121853  12103937          8100        0.0         1.0          0.0        1.0   
121854  12170623         38250        1.0         1.0          0.0        1.0   
121855  12105610          9000        1.0         1.0          1.0        1.0   

        Child_Count Credit_Amount Loan_Annuity Accompany_Client  ...  \
0               0.0      61190.55      3416.85            Alone  ...   
1               0.0         15282      1826.55            Alone  ...   
2               1.0      59527.35       2788.2            Alone  ...   
3               0.0       53870.4      2295.45            Alone  ...   
4               2.0      133988.4      3547.35            Alone  ...   
...             ...           ...          ...              ...  ...   
121851          0.0        107820       3165.3         Relative  ...   
121852          0.0        104256      3388.05            Alone  ...   
121853          1.0       55107.9      2989.35            Alone  ...   
121854          0.0         45000      2719.35            Alone  ...   
121855          1.0      62428.95      4201.65            Alone  ...   

       Client_Permanent_Match_Tag Client_Contact_Work_Tag  \
0                             Yes                     Yes   
1                             Yes                     Yes   
2                             Yes                     Yes   
3                             Yes                     Yes   
4                             Yes                     Yes   
...                           ...                     ...   
121851                        Yes                      No   
121852                        Yes                     Yes   
121853                         No                      No   
121854                        Yes                     Yes   
121855                        Yes                     Yes   

             Type_Organization Score_Source_1 Score_Source_2 Score_Source_3  \
0                Self-employed       0.568066       0.478787            NaN   
1                   Government       0.563360       0.215068            NaN   
2                Self-employed            NaN       0.552795       0.329655   
3                          XNA            NaN       0.135182       0.631355   
4       Business Entity Type 3       0.508199       0.301182       0.355639   
...                        ...            ...            ...            ...   
121851  Business Entity Type 2            NaN       0.173527       0.184116   
121852           Self-employed            NaN       0.371559       0.406617   
121853           Trade: type 6       0.169049       0.048079            NaN   
121854  Business Entity Type 3       0.182737       0.103538       0.077499   
121855  Business Entity Type 3            NaN       0.556414       0.298595   

       Social_Circle_Default Phone_Change Credit_Bureau Default  
0                     0.0186         63.0           NaN       0  
1                        NaN          NaN           NaN       0  
2                     0.0742        277.0           0.0       0  
3                        NaN       1700.0           3.0       0  
4                     0.2021        674.0           1.0       0  
...                      ...          ...           ...     ...  
121851                0.0577    

In [18]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121856 entries, 0 to 121855
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   ID                          121856 non-null  int64  
 1   Client_Income               118249 non-null  object 
 2   Car_Owned                   118275 non-null  float64
 3   Bike_Owned                  118232 non-null  float64
 4   Active_Loan                 118221 non-null  float64
 5   House_Own                   118195 non-null  float64
 6   Child_Count                 118218 non-null  float64
 7   Credit_Amount               118224 non-null  object 
 8   Loan_Annuity                117044 non-null  object 
 9   Accompany_Client            120110 non-null  object 
 10  Client_Income_Type          118155 non-null  object 
 11  Client_Education            118211 non-null  object 
 12  Client_Marital_Status       118383 non-null  object 
 13  Client_Gender 

In [19]:
df_train.nunique()

ID                            121856
Client_Income                   1516
Car_Owned                          2
Bike_Owned                         2
Active_Loan                        2
House_Own                          2
Child_Count                       14
Credit_Amount                   6816
Loan_Annuity                   16680
Accompany_Client                   7
Client_Income_Type                 8
Client_Education                   5
Client_Marital_Status              4
Client_Gender                      3
Loan_Contract_Type                 2
Client_Housing_Type                6
Population_Region_Relative       164
Age_Days                       22583
Employed_Days                  13220
Registration_Days              19254
ID_Days                         9655
Own_House_Age                     55
Mobile_Tag                         2
Homephone_Tag                      2
Workphone_Working                  2
Client_Occupation                 18
Client_Family_Members             15
C

#### DATA PREPROCESSING

In [20]:
df_train.isna().sum()

ID                                0
Client_Income                  3607
Car_Owned                      3581
Bike_Owned                     3624
Active_Loan                    3635
House_Own                      3661
Child_Count                    3638
Credit_Amount                  3632
Loan_Annuity                   4812
Accompany_Client               1746
Client_Income_Type             3701
Client_Education               3645
Client_Marital_Status          3473
Client_Gender                  2413
Loan_Contract_Type             3651
Client_Housing_Type            3687
Population_Region_Relative     4857
Age_Days                       3600
Employed_Days                  3649
Registration_Days              3614
ID_Days                        5968
Own_House_Age                 80095
Mobile_Tag                        0
Homephone_Tag                     0
Workphone_Working                 0
Client_Occupation             41435
Client_Family_Members          2410
Cleint_City_Rating          

In [21]:
# DROPPING ID COLUMN

df_train.drop(["ID"], axis = 1, inplace = True)

df_train.head()

Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  Child_Count  \
0          6750        0.0         0.0          1.0        0.0          0.0   
1         20250        1.0         0.0          1.0        NaN          0.0   
2         18000        0.0         0.0          1.0        0.0          1.0   
3         15750        0.0         0.0          1.0        1.0          0.0   
4         33750        1.0         0.0          1.0        0.0          2.0   

  Credit_Amount Loan_Annuity Accompany_Client Client_Income_Type  ...  \
0      61190.55      3416.85            Alone         Commercial  ...   
1         15282      1826.55            Alone            Service  ...   
2      59527.35       2788.2            Alone            Service  ...   
3       53870.4      2295.45            Alone            Retired  ...   
4      133988.4      3547.35            Alone         Commercial  ...   

  Client_Permanent_Match_Tag Client_Contact_Work_Tag       Type_Organization  \
0                        Yes                     Yes           Self-employed   
1                        Yes                     Yes              Government   
2                        Yes                     Yes           Self-employed   
3                        Yes                     Yes                     XNA   
4                        Yes                     Yes  Business Entity Type 3   

  Score_Source_1 Score_Source_2 Score_Source_3 Social_Circle_Default  \
0       0.568066       0.478787            NaN                0.0186   
1       0.563360       0.215068            NaN                   NaN   
2            NaN       0.552795       0.329655                0.0742   
3            NaN       0.135182       0.631355                   NaN   
4       0.508199       0.301182       0.355639                0.2021   

  Phone_Change Credit_Bureau Default  
0         63.0           NaN       0  
1          NaN           NaN       0  
2        277.0           0.0       0  
3       1700.0           3.0       0  
4        674.0           1.0       0  

[5 rows x 39 columns]

In [22]:
df_train["Client_Income"].tolist()

['6750',
 '20250',
 '18000',
 '15750',
 '33750',
 '11250',
 '15750',
 '13500',
 '13500',
 '12150',
 '27000',
 '15750',
 '27000',
 '8100',
 '22500',
 '45000',
 '11250',
 '13500',
 '15750',
 '9000',
 '18000',
 '27000',
 '15750',
 '18000',
 '19350',
 '22500',
 '31500',
 '11250',
 '21600',
 '27000',
 '20250',
 '22500',
 '11250',
 '15750',
 '4500',
 '18000',
 '35550',
 '32480.55',
 '13500',
 '12150',
 '13950',
 '15750',
 '31500',
 '9000',
 '22500',
 '22500',
 '9000',
 '24750',
 '18000',
 '17100',
 '12600',
 '6750',
 '54000',
 '22500',
 '11250',
 '14400',
 nan,
 '11250',
 '12150',
 '9000',
 '21600',
 '13500',
 '13950',
 '24750',
 '11250',
 '21600',
 '20250',
 '18000',
 '6525',
 '11250',
 '11250',
 '7650',
 '18000',
 '22500',
 '13500',
 '15750',
 '15750',
 '18000',
 '13500',
 '18900',
 '18000',
 '8100',
 '18000',
 '16200',
 '7200',
 '9450',
 '7560',
 '22050',
 '27000',
 '9900',
 '18000',
 '9000',
 '19350',
 '27000',
 '13500',
 '15750',
 '9000',
 '18000',
 '13500',
 '9000',
 '20250',
 '22500',

In [23]:
df_train["Credit_Amount"].tolist()

['61190.55',
 '15282',
 '59527.35',
 '53870.4',
 '133988.4',
 '13752',
 '128835',
 '60415.2',
 '45000',
 '16320.15',
 '67500',
 '149963.85',
 '28440',
 '90000',
 '100424.7',
 '105493.5',
 '29713.05',
 '18000',
 '45000',
 '22500',
 '128835',
 '38053.35',
 '49121.1',
 '77368.05',
 '111384',
 '89660.25',
 '125640',
 '17064',
 '125956.35',
 '38152.8',
 '157500',
 '43787.7',
 '18000',
 '20250',
 '15282',
 '67500',
 '77968.8',
 '13500',
 '201384',
 '25128',
 '80865',
 '60415.2',
 '52823.25',
 '9000',
 '82567.35',
 '125640',
 '28440',
 '77702.4',
 '107820',
 '90000',
 '28440',
 '40500',
 '24750',
 '50326.65',
 '64008',
 '21564',
 '39096',
 '31276.8',
 '80865',
 '90000',
 '112500',
 '22500',
 '30600',
 '103500',
 '36000',
 '41702.4',
 '123681.6',
 '221522.4',
 '28440',
 '27000',
 '97038',
 '24750',
 '36000',
 '14391',
 '45000',
 '15750',
 '125640',
 '168726.6',
 '31410',
 '17064',
 '54504',
 '54000',
 '45000',
 '123681.6',
 '26100',
 '51856.2',
 '28670.4',
 '129350.25',
 '52128',
 '24750',
 '4

In [24]:
# FINDING COLUMNS WITH OBJECT DATA TYPE

df_train.describe(include = "O")

Client_Income  Credit_Amount Loan_Annuity Accompany_Client  \
count         118249       118224.0       117044           120110   
unique          1516         6816.0        16680                7   
top            13500        45000.0          900            Alone   
freq           11908         2513.0         1885            97409   

       Client_Income_Type Client_Education Client_Marital_Status  \
count              118155           118211                118383   
unique                  8                5                     4   
top               Service        Secondary                     M   
freq                61028            83911                 87349   

       Client_Gender Loan_Contract_Type Client_Housing_Type  \
count         119443             118205              118169   
unique             3                  2                   6   
top             Male                 CL                Home   
freq           78463             107118              104870   

       Population_Region_Relative Age_Days Employed_Days Registration_Days  \
count                      116999   118256        118207            118242   
unique                        164    22583         13220             19254   
top                      0.035792    10065        365243                 1   
freq                         4159       20         19848                44   

       ID_Days Client_Occupation Client_Permanent_Match_Tag  \
count   115888             80421                     121856   
unique    9655                18                          2   
top       4053          Laborers                        Yes   
freq        73             21024                     112454   

       Client_Contact_Work_Tag       Type_Organization  Score_Source_3  
count                   121856                  118247      94935.0000  
unique                       2                      58       1430.0000  
top                        Yes  Business Entity Type 3          0.7463  
freq                    100015                   26279        484.0000

#### CONVERTING ABOVE OBJECT DATA TYPE COLUMNS TO NUMERIC

In [25]:
# REPLACING $ IN DATA TO NAN AND THEN CONVERTING TO NUMERIC

df_train.Client_Income.replace("$", np.nan, inplace = True)

df_train.Client_Income = pd.to_numeric(df_train.Client_Income)

In [26]:
df_train["Client_Income"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 121856 entries, 0 to 121855
Series name: Client_Income
Non-Null Count   Dtype  
--------------   -----  
118234 non-null  float64
dtypes: float64(1)
memory usage: 952.1 KB


In [27]:
df_train.Credit_Amount.replace(["#VALUE!", "$"], np.nan, inplace = True)

df_train.Credit_Amount = pd.to_numeric(df_train.Credit_Amount)

In [28]:
df_train.Loan_Annuity.replace(["#VALUE!", "$"], np.nan, inplace = True)

df_train.Loan_Annuity = pd.to_numeric(df_train.Loan_Annuity)

In [29]:
df_train.Age_Days.replace("x", np.nan, inplace = True)

df_train.Age_Days = pd.to_numeric(df_train.Age_Days)

In [30]:
df_train.Employed_Days.replace("x", np.nan, inplace = True)

df_train.Employed_Days = pd.to_numeric(df_train.Employed_Days)

In [31]:
df_train.Registration_Days.replace("x", np.nan, inplace = True)

df_train.Registration_Days = pd.to_numeric(df_train.Registration_Days)

In [32]:
df_train.ID_Days.replace("x", np.nan, inplace = True)

df_train.ID_Days = pd.to_numeric(df_train.ID_Days)

In [33]:
df_train["Score_Source_3"].replace("&", np.nan, inplace = True)

df_train.Score_Source_3 = pd.to_numeric(df_train.Score_Source_3)

In [34]:
# NEW COLUMN IS CREATED ON THE BASIS OF POPULATION_REGION_RELATIVE COLUMN WHETHER THE CLIENT AREA IS POPULATED AREA OR NOT

df_train["Population_Region_Relative"].replace(["#","@"], np.nan, inplace=True)

df_train.Population_Region_Relative = pd.to_numeric(df_train.Population_Region_Relative)

populated_Region_mean = df_train.Population_Region_Relative.mean()

temp = df_train.copy()

temp[temp["Population_Region_Relative"] < populated_Region_mean] = 0 # 0 for less populated area

temp[temp["Population_Region_Relative"] >= populated_Region_mean] = 1 # 1 for high populated area

df_train["Population_Region_Relative"] = temp["Population_Region_Relative"]

In [35]:
df_train.head()

Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  Child_Count  \
0         6750.0        0.0         0.0          1.0        0.0          0.0   
1        20250.0        1.0         0.0          1.0        NaN          0.0   
2        18000.0        0.0         0.0          1.0        0.0          1.0   
3        15750.0        0.0         0.0          1.0        1.0          0.0   
4        33750.0        1.0         0.0          1.0        0.0          2.0   

   Credit_Amount  Loan_Annuity Accompany_Client Client_Income_Type  ...  \
0       61190.55       3416.85            Alone         Commercial  ...   
1       15282.00       1826.55            Alone            Service  ...   
2       59527.35       2788.20            Alone            Service  ...   
3       53870.40       2295.45            Alone            Retired  ...   
4      133988.40       3547.35            Alone         Commercial  ...   

  Client_Permanent_Match_Tag Client_Contact_Work_Tag       Type_Organization  \
0                        Yes                     Yes           Self-employed   
1                        Yes                     Yes              Government   
2                        Yes                     Yes           Self-employed   
3                        Yes                     Yes                     XNA   
4                        Yes                     Yes  Business Entity Type 3   

  Score_Source_1 Score_Source_2  Score_Source_3  Social_Circle_Default  \
0       0.568066       0.478787             NaN                 0.0186   
1       0.563360       0.215068             NaN                    NaN   
2            NaN       0.552795        0.329655                 0.0742   
3            NaN       0.135182        0.631355                    NaN   
4       0.508199       0.301182        0.355639                 0.2021   

   Phone_Change  Credit_Bureau  Default  
0          63.0            NaN        0  
1           NaN            NaN        0  
2         277.0            0.0        0  
3        1700.0            3.0        0  
4         674.0            1.0        0  

[5 rows x 39 columns]

In [36]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121856 entries, 0 to 121855
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Client_Income               118234 non-null  float64
 1   Car_Owned                   118275 non-null  float64
 2   Bike_Owned                  118232 non-null  float64
 3   Active_Loan                 118221 non-null  float64
 4   House_Own                   118195 non-null  float64
 5   Child_Count                 118218 non-null  float64
 6   Credit_Amount               118219 non-null  float64
 7   Loan_Annuity                117030 non-null  float64
 8   Accompany_Client            120110 non-null  object 
 9   Client_Income_Type          118155 non-null  object 
 10  Client_Education            118211 non-null  object 
 11  Client_Marital_Status       118383 non-null  object 
 12  Client_Gender               119443 non-null  object 
 13  Loan_Contract_

In [37]:
df_train.isna().sum()

Client_Income                  3622
Car_Owned                      3581
Bike_Owned                     3624
Active_Loan                    3635
House_Own                      3661
Child_Count                    3638
Credit_Amount                  3637
Loan_Annuity                   4826
Accompany_Client               1746
Client_Income_Type             3701
Client_Education               3645
Client_Marital_Status          3473
Client_Gender                  2413
Loan_Contract_Type             3651
Client_Housing_Type            3687
Population_Region_Relative     4868
Age_Days                       3617
Employed_Days                  3666
Registration_Days              3631
ID_Days                        5985
Own_House_Age                 80095
Mobile_Tag                        0
Homephone_Tag                     0
Workphone_Working                 0
Client_Occupation             41435
Client_Family_Members          2410
Cleint_City_Rating             2409
Application_Process_Day     

In [39]:
# DROPPING COLUMNS WITH MORE THAN 50% NULL VALUES

df_train.drop(columns = ["Own_House_Age", "Score_Source_1", "Social_Circle_Default"], axis = 1, inplace = True)

df_train.head()

Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  Child_Count  \
0         6750.0        0.0         0.0          1.0        0.0          0.0   
1        20250.0        1.0         0.0          1.0        NaN          0.0   
2        18000.0        0.0         0.0          1.0        0.0          1.0   
3        15750.0        0.0         0.0          1.0        1.0          0.0   
4        33750.0        1.0         0.0          1.0        0.0          2.0   

   Credit_Amount  Loan_Annuity Accompany_Client Client_Income_Type  ...  \
0       61190.55       3416.85            Alone         Commercial  ...   
1       15282.00       1826.55            Alone            Service  ...   
2       59527.35       2788.20            Alone            Service  ...   
3       53870.40       2295.45            Alone            Retired  ...   
4      133988.40       3547.35            Alone         Commercial  ...   

  Application_Process_Day Application_Process_Hour Client_Permanent_Match_Tag  \
0                     6.0                     17.0                        Yes   
1                     3.0                     10.0                        Yes   
2                     4.0                      NaN                        Yes   
3                     2.0                     15.0                        Yes   
4                     3.0                      NaN                        Yes   

  Client_Contact_Work_Tag       Type_Organization  Score_Source_2  \
0                     Yes           Self-employed        0.478787   
1                     Yes              Government        0.215068   
2                     Yes           Self-employed        0.552795   
3                     Yes                     XNA        0.135182   
4                     Yes  Business Entity Type 3        0.301182   

   Score_Source_3  Phone_Change  Credit_Bureau  Default  
0             NaN          63.0            NaN        0  
1             NaN           NaN            NaN        0  
2        0.329655         277.0            0.0        0  
3        0.631355        1700.0            3.0        0  
4        0.355639         674.0            1.0        0  

[5 rows x 36 columns]

In [40]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121856 entries, 0 to 121855
Data columns (total 36 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Client_Income               118234 non-null  float64
 1   Car_Owned                   118275 non-null  float64
 2   Bike_Owned                  118232 non-null  float64
 3   Active_Loan                 118221 non-null  float64
 4   House_Own                   118195 non-null  float64
 5   Child_Count                 118218 non-null  float64
 6   Credit_Amount               118219 non-null  float64
 7   Loan_Annuity                117030 non-null  float64
 8   Accompany_Client            120110 non-null  object 
 9   Client_Income_Type          118155 non-null  object 
 10  Client_Education            118211 non-null  object 
 11  Client_Marital_Status       118383 non-null  object 
 12  Client_Gender               119443 non-null  object 
 13  Loan_Contract_

In [43]:
from sklearn.impute import SimpleImputer

si_mean = SimpleImputer(strategy = "mean", missing_values = np.nan)

si_mode = SimpleImputer(strategy = "most_frequent", missing_values = np.nan)

In [44]:
# APPLYING MODE

df_train.iloc[:, 0 : 5] = si_mode.fit_transform(df_train.iloc[:, 0 : 5])

df_train.iloc[:, 8 : 16] = si_mode.fit_transform(df_train.iloc[:, 8 : 16])

df_train.iloc[:, 20 : 31] = si_mode.fit_transform(df_train.iloc[:, 20 : 31])

df_train.iloc[:, 34 : 35] = si_mode.fit_transform(df_train.iloc[:, 34 : 35])

In [45]:
### APPLYING MEAN

df_train.iloc[:, 6 : 8] = si_mean.fit_transform(df_train.iloc[:, 6 : 8])

df_train.iloc[:, 31 : 34] = si_mean.fit_transform(df_train.iloc[:, 31 : 34])

In [46]:
# APPLYING MEAN WITH ROUND FUNCTION FOR REQ COLUMNS

df_train.iloc[:, 5 : 6] = np.round(si_mean.fit_transform(df_train.iloc[:, 5 : 6]))

df_train.iloc[:, 16 : 20] = np.round(si_mean.fit_transform(df_train.iloc[:, 16 : 20]))

In [47]:
df_train.isna().sum()

Client_Income                 0
Car_Owned                     0
Bike_Owned                    0
Active_Loan                   0
House_Own                     0
Child_Count                   0
Credit_Amount                 0
Loan_Annuity                  0
Accompany_Client              0
Client_Income_Type            0
Client_Education              0
Client_Marital_Status         0
Client_Gender                 0
Loan_Contract_Type            0
Client_Housing_Type           0
Population_Region_Relative    0
Age_Days                      0
Employed_Days                 0
Registration_Days             0
ID_Days                       0
Mobile_Tag                    0
Homephone_Tag                 0
Workphone_Working             0
Client_Occupation             0
Client_Family_Members         0
Cleint_City_Rating            0
Application_Process_Day       0
Application_Process_Hour      0
Client_Permanent_Match_Tag    0
Client_Contact_Work_Tag       0
Type_Organization             0
Score_So

In [48]:
df_train["Accompany_Client"].unique()

array(['Alone', 'Relative', 'Others', 'Kids', 'Partner', '##', 'Group'],
      dtype=object)

In [49]:
# LABEL ENCODING FOR CATEGORICAL COLUMNS

from sklearn.preprocessing import LabelEncoder

cols = ["Accompany_Client", "Client_Marital_Status", "Client_Income_Type", "Client_Education", "Client_Gender", "Loan_Contract_Type", "Client_Housing_Type", "Client_Occupation", "Client_Permanent_Match_Tag", "Client_Contact_Work_Tag", "Type_Organization"]

df_train[cols] = df_train[cols].apply(LabelEncoder().fit_transform)

In [50]:
df_train.head()

Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  Child_Count  \
0         6750.0        0.0         0.0          1.0        0.0          0.0   
1        20250.0        1.0         0.0          1.0        1.0          0.0   
2        18000.0        0.0         0.0          1.0        0.0          1.0   
3        15750.0        0.0         0.0          1.0        1.0          0.0   
4        33750.0        1.0         0.0          1.0        0.0          2.0   

   Credit_Amount  Loan_Annuity  Accompany_Client  Client_Income_Type  ...  \
0       61190.55       3416.85                 1                   1  ...   
1       15282.00       1826.55                 1                   5  ...   
2       59527.35       2788.20                 1                   5  ...   
3       53870.40       2295.45                 1                   4  ...   
4      133988.40       3547.35                 1                   1  ...   

   Application_Process_Day  Application_Process_Hour  \
0                      6.0                      17.0   
1                      3.0                      10.0   
2                      4.0                      10.0   
3                      2.0                      15.0   
4                      3.0                      10.0   

   Client_Permanent_Match_Tag  Client_Contact_Work_Tag  Type_Organization  \
0                           1                        1                 42   
1                           1                        1                 11   
2                           1                        1                 42   
3                           1                        1                 57   
4                           1                        1                  5   

   Score_Source_2  Score_Source_3  Phone_Change  Credit_Bureau  Default  
0        0.478787        0.511180     63.000000            0.0        0  
1        0.215068        0.511180    962.106056            0.0        0  
2        0.552795        0.329655    277.000000            0.0        0  
3        0.135182        0.631355   1700.000000            3.0        0  
4        0.301182        0.355639    674.000000            1.0        0  

[5 rows x 36 columns]

In [51]:
df_train['Accompany_Client'].unique()

array([1, 6, 4, 3, 5, 0, 2])

In [52]:
df_train['Client_Marital_Status'].unique()

array([1, 3, 2, 0])

In [53]:
df_train['Client_Income_Type'].unique()

array([1, 5, 4, 2, 6, 7, 3, 0])

In [54]:
df_train['Client_Education'].unique()

array([4, 0, 1, 2, 3])

In [55]:
df_train['Client_Gender'].unique()

array([1, 0, 2])

In [56]:
df_train['Loan_Contract_Type'].unique()

array([0, 1])

In [57]:
df_train['Client_Housing_Type'].unique()

array([1, 0, 3, 2, 4, 5])

In [58]:
df_train['Client_Occupation'].unique()

array([14,  8, 13,  3,  4, 10,  0,  6,  1,  5, 17,  9, 11,  2, 12, 16,  7,
       15])

In [59]:
df_train['Type_Organization'].unique()

array([42, 11, 57,  5, 33, 20,  4,  3, 55,  7, 28, 47, 19, 51, 46,  1, 31,
       30, 13, 14, 16,  2, 39, 26, 35, 56, 53, 38,  9, 34, 21, 41, 43, 54,
       32, 12, 40, 24,  0,  6, 36, 50,  8, 22, 44, 45, 17, 25, 27, 10, 29,
       15, 48, 23, 52, 18, 37, 49])

In [60]:
df_train['Client_Permanent_Match_Tag'].unique()

array([1, 0])

In [61]:
df_train['Client_Contact_Work_Tag'].unique()

array([1, 0])

#### MODEL TRAINING

In [62]:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score,auc,roc_curve,f1_score, recall_score, precision_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
import pickle
from imblearn.combine import SMOTETomek


In [63]:
X = df_train.drop("Default", axis = 1)

y = df_train["Default"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [64]:
rf_classifier = RandomForestClassifier()

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy_score(y_test, y_pred) * 100

93.0288856064336

In [92]:
dt_classifier = DecisionTreeClassifier()

dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_test)

accuracy_score(y_test, y_pred) * 100

90.41310828682224

In [93]:
#training_score = []

#testing_score = []

def accuracy_check(x,y,models):
    
    # TRAIN TEST SPLIT
    
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
    
    model=models().fit(x_train,y_train)
    
    y_trainpred=model.predict(x_train)
    
    y_testpred=model.predict(x_test)
    
    # CHECKING THE accuracy_score
    
    accuracy_train=accuracy_score(y_train,y_trainpred)
    
    accuracy_test=accuracy_score(y_test,y_testpred)
    
    Precision_score=precision_score(y_test,y_testpred)
    
    Recall_score=recall_score(y_test,y_testpred)
    
    F1_Score=f1_score(y_test,y_testpred)

    metrics={"Model": models.__name__,
            "Accuracy_Train":accuracy_train,
            "Accuracy_Test":accuracy_test,
            "Precision_score":Precision_score,
             "Recall_score":Recall_score,
             "F1_score":F1_Score
            }
    
    return metrics

In [94]:
accuracy_check(X,y,LogisticRegression)

{'Model': 'LogisticRegression',
 'Accuracy_Train': 0.9187558984038406,
 'Accuracy_Test': 0.9210159199080913,
 'Precision_score': np.float64(0.0),
 'Recall_score': np.float64(0.0),
 'F1_score': np.float64(0.0)}

In [95]:
accuracy_check(X,y,KNeighborsClassifier)

{'Model': 'KNeighborsClassifier',
 'Accuracy_Train': 0.9233104919781707,
 'Accuracy_Test': 0.9096504185130477,
 'Precision_score': np.float64(0.1951219512195122),
 'Recall_score': np.float64(0.027627035027133696),
 'F1_score': np.float64(0.04840103716508211)}

In [96]:
accuracy_check(X,y,DecisionTreeClassifier)

{'Model': 'DecisionTreeClassifier',
 'Accuracy_Train': 1.0,
 'Accuracy_Test': 0.8687428196290825,
 'Precision_score': np.float64(0.25573491928632114),
 'Recall_score': np.float64(0.29380185456320157),
 'F1_score': np.float64(0.27344992050874406)}

In [98]:
accuracy_check(X,y,RandomForestClassifier)

{'Model': 'RandomForestClassifier',
 'Accuracy_Train': 0.9999897419063641,
 'Accuracy_Test': 0.930822255046775,
 'Precision_score': np.float64(0.9881889763779528),
 'Recall_score': np.float64(0.1297828335056877),
 'F1_score': np.float64(0.22943327239488118)}

In [99]:
accuracy_check(X,y,AdaBoostClassifier)

{'Model': 'AdaBoostClassifier',
 'Accuracy_Train': 0.9190123507447376,
 'Accuracy_Test': 0.9206466436894797,
 'Precision_score': np.float64(0.47761194029850745),
 'Recall_score': np.float64(0.016571724495080268),
 'F1_score': np.float64(0.03203203203203203)}

#### SAVE THE FILE

In [100]:
df_train.to_csv("Vehicle_Loan_Train_Data.csv",index=False)

In [101]:
data = pd.read_csv(r"C:\Users\HP\SPJP\Vehicle_Loan_Train_Data.csv")

data.head()

Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  Child_Count  \
0         6750.0        0.0         0.0          1.0        0.0          0.0   
1        20250.0        1.0         0.0          1.0        1.0          0.0   
2        18000.0        0.0         0.0          1.0        0.0          1.0   
3        15750.0        0.0         0.0          1.0        1.0          0.0   
4        33750.0        1.0         0.0          1.0        0.0          2.0   

   Credit_Amount  Loan_Annuity  Accompany_Client  Client_Income_Type  ...  \
0       61190.55       3416.85                 1                   1  ...   
1       15282.00       1826.55                 1                   5  ...   
2       59527.35       2788.20                 1                   5  ...   
3       53870.40       2295.45                 1                   4  ...   
4      133988.40       3547.35                 1                   1  ...   

   Application_Process_Day  Application_Process_Hour  \
0                      6.0                      17.0   
1                      3.0                      10.0   
2                      4.0                      10.0   
3                      2.0                      15.0   
4                      3.0                      10.0   

   Client_Permanent_Match_Tag  Client_Contact_Work_Tag  Type_Organization  \
0                           1                        1                 42   
1                           1                        1                 11   
2                           1                        1                 42   
3                           1                        1                 57   
4                           1                        1                  5   

   Score_Source_2  Score_Source_3  Phone_Change  Credit_Bureau  Default  
0        0.478787        0.511180     63.000000            0.0        0  
1        0.215068        0.511180    962.106056            0.0        0  
2        0.552795        0.329655    277.000000            0.0        0  
3        0.135182        0.631355   1700.000000            3.0        0  
4        0.301182        0.355639    674.000000            1.0        0  

[5 rows x 36 columns]

#### SAMPLING TO MAKE THE DATA BALANCED

In [102]:
# DO SAMPLING TO MAKE THE DATA BALANCED

data['Default'].value_counts()

Default
0    112011
1      9845
Name: count, dtype: int64

In [103]:
x = data.drop(columns=["Default"],axis=1)

y = data["Default"]

In [104]:
# DO SAMPLING TO MAKE COUNT BALANCED SYNTHETIC MINORITY OVERSAMPLING TECHNIQUE

x_new,y_new = SMOTETomek().fit_resample(x,y)

In [105]:
y_new.value_counts()

Default
0    111505
1    111505
Name: count, dtype: int64

In [106]:
# ACCURACY AFTER SAMPLING

accuracy_check(x_new, y_new, DecisionTreeClassifier)

{'Model': 'DecisionTreeClassifier',
 'Accuracy_Train': 1.0,
 'Accuracy_Test': 0.9129859647549438,
 'Precision_score': np.float64(0.9066067257261228),
 'Recall_score': np.float64(0.9210997671502776),
 'F1_score': np.float64(0.9137957841896004)}

In [107]:
# ACCURACY AFTER SAMPLING

accuracy_check(x_new,y_new,RandomForestClassifier) 

{'Model': 'RandomForestClassifier',
 'Accuracy_Train': 0.9999943948701852,
 'Accuracy_Test': 0.9636339177615354,
 'Precision_score': np.float64(0.9986018031917459),
 'Recall_score': np.float64(0.9285810356422327),
 'F1_score': np.float64(0.9623193792686893)}

In [108]:
X_train,x_test,y_train,y_test=train_test_split(x_new,y_new,test_size=0.4,random_state=11)

model = DecisionTreeClassifier().fit(X_train,y_train)

y_pred_train=model.predict(X_train)

y_pred_test=model.predict(x_test)

# CHECKING THE ACCURACY SCORE OF TRAIN AND TEST DATA

accuracy_train=accuracy_score(y_train,y_pred_train)

accuracy_test=accuracy_score(y_test,y_pred_test)

print("Accuracy scores of train and test data")

print("Train_Accuracy",accuracy_train)

print("Test_Accuracy",accuracy_test)

print("Confusion_matrix for Test")

print(confusion_matrix(y_true= y_test, y_pred= y_pred_test))

Accuracy scores of train and test data
Train_Accuracy 1.0
Test_Accuracy 0.9045558495134748
Confusion_matrix for Test
[[39548  4699]
 [ 3815 41142]]


In [109]:
model.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [110]:
X_train,x_test,y_train,y_test=train_test_split(x_new,y_new,test_size=0.2,random_state=42)

model=RandomForestClassifier().fit(X_train,y_train)

y_pred_train=model.predict(X_train)

y_pred_test=model.predict(x_test)

# CHECKING THE ACCURACY SCORE OF TRAIN AND TEST DATA

accuracy_train=accuracy_score(y_train,y_pred_train)

accuracy_test=accuracy_score(y_test,y_pred_test)

print("Accuracy scores of train and test data")

print("Train_Accuracy",accuracy_train)

print("Test_Accuracy",accuracy_test)

print("Confusion_matrix for Test")

print(confusion_matrix(y_true= y_test, y_pred= y_pred_test))

Accuracy scores of train and test data
Train_Accuracy 0.9999887897403704
Test_Accuracy 0.9641047486659791
Confusion_matrix for Test
[[22244    28]
 [ 1573 20757]]


In [111]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [114]:
X_train, X_test, y_train, y_test = train_test_split(x_new, y_new, test_size=0.20, random_state=42)

from sklearn.model_selection import GridSearchCV

param_grid = { 
                'n_estimators': [100,200, 300],
                #'max_features': ['sqrt','log2'], 
                #'max_depth': [None,50], 
                #'max_leaf_nodes': [None,3, 6, 9],
                'min_samples_split': [2, 3, 4],
                'min_samples_leaf': [1, 2, 3]
                    
            } 

grid_search = GridSearchCV(RandomForestClassifier(), 
                           param_grid=param_grid,cv=3,n_jobs=-1,verbose=2) 

grid_search.fit(X_train, y_train) 

print(grid_search.best_estimator_)

Fitting 3 folds for each of 27 candidates, totalling 81 fits
RandomForestClassifier(n_estimators=200)


In [115]:
grid_search.best_params_

{'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}

In [116]:
X_train,x_test,y_train,y_test=train_test_split(x_new,y_new,test_size=0.2,random_state=42)

model=RandomForestClassifier(min_samples_leaf=1,max_features="sqrt",min_samples_split=2,n_estimators=200).fit(X_train,y_train)

y_pred_train=model.predict(X_train)

y_pred_test=model.predict(x_test)

#checking the accuracy score of train and test data

accuracy_train=accuracy_score(y_train,y_pred_train)

accuracy_test=accuracy_score(y_test,y_pred_test)

print("Accuracy scores of train and test data")

print("Train_Accuracy",accuracy_train)

print("Test_Accuracy",accuracy_test)

print("Confusion_matrix for Test")

print(confusion_matrix(y_true= y_test, y_pred= y_pred_test))

Accuracy scores of train and test data
Train_Accuracy 1.0
Test_Accuracy 0.9640823281467199
Confusion_matrix for Test
[[22241    31]
 [ 1571 20759]]


In [117]:
data.to_csv("Vehicle_Loan_Train_Data_AS.csv", index = False)

In [119]:
data_AS = pd.read_csv(r"C:\Users\HP\SPJP\Vehicle_Loan_Train_Data.csv")

data_AS.head()

Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  Child_Count  \
0         6750.0        0.0         0.0          1.0        0.0          0.0   
1        20250.0        1.0         0.0          1.0        1.0          0.0   
2        18000.0        0.0         0.0          1.0        0.0          1.0   
3        15750.0        0.0         0.0          1.0        1.0          0.0   
4        33750.0        1.0         0.0          1.0        0.0          2.0   

   Credit_Amount  Loan_Annuity  Accompany_Client  Client_Income_Type  ...  \
0       61190.55       3416.85                 1                   1  ...   
1       15282.00       1826.55                 1                   5  ...   
2       59527.35       2788.20                 1                   5  ...   
3       53870.40       2295.45                 1                   4  ...   
4      133988.40       3547.35                 1                   1  ...   

   Application_Process_Day  Application_Process_Hour  \
0                      6.0                      17.0   
1                      3.0                      10.0   
2                      4.0                      10.0   
3                      2.0                      15.0   
4                      3.0                      10.0   

   Client_Permanent_Match_Tag  Client_Contact_Work_Tag  Type_Organization  \
0                           1                        1                 42   
1                           1                        1                 11   
2                           1                        1                 42   
3                           1                        1                 57   
4                           1                        1                  5   

   Score_Source_2  Score_Source_3  Phone_Change  Credit_Bureau  Default  
0        0.478787        0.511180     63.000000            0.0        0  
1        0.215068        0.511180    962.106056            0.0        0  
2        0.552795        0.329655    277.000000            0.0        0  
3        0.135182        0.631355   1700.000000            3.0        0  
4        0.301182        0.355639    674.000000            1.0        0  

[5 rows x 36 columns]

In [120]:
with open("VehicleLoan_Classification_Model_AFHP.pkl","wb") as f:
    
    pickle.dump(model,f)

In [121]:
with open("VehicleLoan_Classification_Model_AFHP.pkl","rb") as f1:
    
    class_model_afhp= pickle.load(f1)

### SAMPLE DATA TESTING

In [122]:
df=pd.DataFrame({
                 'Client_Income':11250,
                 'Car_Owned':0,
                 'Bike_Owned':1,
                 'Active_Loan':1,
                 'House_Own':1,
                 'Child_Count':1,
                 'Credit_Amount':91800,
                'Loan_Annuity':2683.8,
                'Accompany_Client':1,
                'Client_Income_Type':5,
                'Client_Education':4,
                'Client_Marital_Status':2,
                'Client_Gender':0,
                'Loan_Contract_Type':0,
                'Client_Housing_Type':1,
                'Population_Region_Relative':1,
                'Age_Days':9899,
                'Employed_Days':1892,
                'Registration_Days':477,
                'ID_Days':2571,
                'Mobile_Tag':1,
                'Homephone_Tag':1,
                'Workphone_Working':1,
                'Client_Occupation':8,
                'Client_Family_Members':2,
                'Cleint_City_Rating':2,
                'Application_Process_Day':6,
               'Application_Process_Hour':11,
                'Client_Permanent_Match_Tag':1,
                'Client_Contact_Work_Tag':0,
                'Type_Organization':5,
                'Score_Source_2':0.495404,
                'Score_Source_3':0.51118,
                'Phone_Change':1629,
                'Credit_Bureau':0},index=[0])

In [123]:
y_p=class_model_afhp.predict(df)

if(y_p==0):
    
  print("No Default")
  
else:
    
  print("Default")

No Default


In [124]:
df1=pd.DataFrame({
                 'Client_Income':7650,
                 'Car_Owned':0,
                 'Bike_Owned':0,
                 'Active_Loan':0,
                 'House_Own':0,
                 'Child_Count':0,
                 'Credit_Amount':13500,
                'Loan_Annuity':675,
                'Accompany_Client':1,
                'Client_Income_Type':5,
                'Client_Education':4,
                'Client_Marital_Status':1,
                'Client_Gender':1,
                'Loan_Contract_Type':1,
                'Client_Housing_Type':4,
                'Population_Region_Relative':0,
                'Age_Days':16969,
                'Employed_Days':1214,
                'Registration_Days':8663,
                'ID_Days':4536,
                'Mobile_Tag':1,
                'Homephone_Tag':0,
                'Workphone_Working':0,
                'Client_Occupation':1,
                'Client_Family_Members':2,
                'Cleint_City_Rating':2,
                'Application_Process_Day':2,
               'Application_Process_Hour':14,
                'Client_Permanent_Match_Tag':1,
                'Client_Contact_Work_Tag':1,
                'Type_Organization':42,
                'Score_Source_2':0.349477,
                'Score_Source_3':0.51118,
                'Phone_Change':0,
                'Credit_Bureau':0},index=[0])

In [125]:
y_p=class_model_afhp.predict(df1)

if(y_p==0):
    
  print("No Default")
  
else:
    
  print("Default")

No Default


In [126]:
df2=pd.DataFrame({
                 'Client_Income':12150,
                 'Car_Owned':1,
                 'Bike_Owned':0,
                 'Active_Loan':0,
                 'House_Own':1,
                 'Child_Count':0,
                 'Credit_Amount':80865,
                'Loan_Annuity':2721.254,
                'Accompany_Client':6,
                'Client_Income_Type':4,
                'Client_Education':4,
                'Client_Marital_Status':1,
                'Client_Gender':0,
                'Loan_Contract_Type':0,
                'Client_Housing_Type':1,
                'Population_Region_Relative':0,
                'Age_Days':19738,
                'Employed_Days':365243,
                'Registration_Days':4975,
                'ID_Days':2987,
                'Mobile_Tag':1,
                'Homephone_Tag':0,
                'Workphone_Working':0,
                'Client_Occupation':8,
                'Client_Family_Members':2,
                'Cleint_City_Rating':2,
                'Application_Process_Day':6,
               'Application_Process_Hour':10,
                'Client_Permanent_Match_Tag':0,
                'Client_Contact_Work_Tag':1,
                'Type_Organization':57,
                'Score_Source_2':0.35341,
                'Score_Source_3':0.225087,
                'Phone_Change':190,
                'Credit_Bureau':2},index=[0])

In [127]:
y_p=class_model_afhp.predict(df2)

if(y_p==0):
    
  print("No Default")
  
else:
    
  print("Default")

Default


### TESTING DATA PREDICTION

In [174]:
df_test = pd.read_csv(r"C:\Users\HP\Downloads\Test_Dataset.csv.zip")

df_test

ID Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  \
0      12202227         11250        0.0         1.0          1.0        1.0   
1      12279381         13500        1.0         1.0          1.0        1.0   
2      12222714         38250        0.0         1.0          0.0        1.0   
3      12265215         20250        0.0         0.0          1.0        0.0   
4      12203970         13500        1.0         1.0          0.0        1.0   
...         ...           ...        ...         ...          ...        ...   
80895  12210181         11700        0.0         0.0          0.0        1.0   
80896  12206257         29250        0.0         1.0          1.0        1.0   
80897  12200446         54000        1.0         0.0          1.0        1.0   
80898  12244943         13500        0.0         0.0          1.0        0.0   
80899  12229890         10350        1.0         0.0          0.0        0.0   

       Child_Count Credit_Amount Loan_Annuity Accompany_Client  ...  \
0              0.0        112500       4474.8         Relative  ...   
1              3.0         49752      3252.15            Alone  ...   
2              0.0         67500         3375            Alone  ...   
3              0.0      50849.55      3814.65            Alone  ...   
4              0.0       43603.2      2515.95            Alone  ...   
...            ...           ...          ...              ...  ...   
80895          2.0        107820      3152.25            Alone  ...   
80896          2.0     116430.75       4630.5            Alone  ...   
80897          0.0         52128       2742.3            Alone  ...   
80898          0.0         25470      1435.05            Alone  ...   
80899          1.0         26955       1475.1            Alone  ...   

      Application_Process_Hour Client_Permanent_Match_Tag  \
0                         16.0                        Yes   
1                         18.0                         No   
2                         19.0                        Yes   
3                         20.0                         No   
4                         13.0                        Yes   
...                        ...                        ...   
80895                      9.0                        Yes   
80896                     15.0                        Yes   
80897                     14.0                        Yes   
80898                      5.0                        Yes   
80899                      9.0                        Yes   

      Client_Contact_Work_Tag       Type_Organization Score_Source_1  \
0                         Yes           Self-employed            NaN   
1                         Yes           Self-employed            NaN   
2                         Yes  Business Entity Type 3            NaN   
3                          No                Medicine       0.351581   
4                         Yes           Self-employed       0.731110   
...                       ...                     ...            ...   
80895                      No           Self-employed       0.495015   
80896                     Yes            Kindergarten       0.803057   
80897                      No           Self-employed            NaN   
80898                     Yes        Industry: type 9            NaN   
80899                     Yes  Business Entity Type 2       0.127368   

      Score_Source_2 Score_Source_3 Social_Circle_Default Phone_Change  \
0           0.757151       0.629674                0.0515        716.0   
1           0.342269            NaN                   NaN        181.0   
2           0.683665            NaN                0.1503        281.0   
3            0.22995       0.672243                   NaN       1442.0   
4           0.566971       0.730987                   NaN        927.0   
...              ...            ...                   ...          ...   
80895       0.599436    0.276440695                   NaN        537.0   
80896    

In [175]:
df_test.isna().sum()

ID                                0
Client_Income                  2434
Car_Owned                      2405
Bike_Owned                     2486
Active_Loan                    2454
House_Own                      2347
Child_Count                    2328
Credit_Amount                  2287
Loan_Annuity                   3203
Accompany_Client               1208
Client_Income_Type             2501
Client_Education               2350
Client_Marital_Status          2443
Client_Gender                  1627
Loan_Contract_Type             2321
Client_Housing_Type            2408
Population_Region_Relative     3270
Age_Days                       2479
Employed_Days                  2421
Registration_Days              2398
ID_Days                        3881
Own_House_Age                 53581
Mobile_Tag                        0
Homephone_Tag                     0
Workphone_Working                 0
Client_Occupation             27845
Client_Family_Members          1644
Cleint_City_Rating          

In [176]:
#dropping columns with more than 50% null value

df_test.drop(columns=["Own_House_Age","Score_Source_1","Social_Circle_Default"],axis=1,inplace=True)

df_test.head(3)

ID Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  \
0  12202227         11250        0.0         1.0          1.0        1.0   
1  12279381         13500        1.0         1.0          1.0        1.0   
2  12222714         38250        0.0         1.0          0.0        1.0   

   Child_Count Credit_Amount Loan_Annuity Accompany_Client  ...  \
0          0.0        112500       4474.8         Relative  ...   
1          3.0         49752      3252.15            Alone  ...   
2          0.0         67500         3375            Alone  ...   

  Cleint_City_Rating Application_Process_Day Application_Process_Hour  \
0                2.0                     4.0                     16.0   
1                3.0                     3.0                     18.0   
2                1.0                     2.0                     19.0   

  Client_Permanent_Match_Tag Client_Contact_Work_Tag       Type_Organization  \
0                        Yes                     Yes           Self-employed   
1                         No                     Yes           Self-employed   
2                        Yes                     Yes  Business Entity Type 3   

  Score_Source_2 Score_Source_3 Phone_Change Credit_Bureau  
0       0.757151       0.629674        716.0           2.0  
1       0.342269            NaN        181.0           NaN  
2       0.683665            NaN        281.0           NaN  

[3 rows x 36 columns]

In [177]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80900 entries, 0 to 80899
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   ID                          80900 non-null  int64  
 1   Client_Income               78466 non-null  object 
 2   Car_Owned                   78495 non-null  float64
 3   Bike_Owned                  78414 non-null  float64
 4   Active_Loan                 78446 non-null  float64
 5   House_Own                   78553 non-null  float64
 6   Child_Count                 78572 non-null  float64
 7   Credit_Amount               78613 non-null  object 
 8   Loan_Annuity                77697 non-null  object 
 9   Accompany_Client            79692 non-null  object 
 10  Client_Income_Type          78399 non-null  object 
 11  Client_Education            78550 non-null  object 
 12  Client_Marital_Status       78457 non-null  object 
 13  Client_Gender               792

In [178]:
# Converting the columns to Numeric datatypes

df_test.Client_Income.replace("$", np.nan, inplace = True)

df_test.Client_Income = pd.to_numeric(df_test.Client_Income)

In [179]:
df_test.Credit_Amount.replace("$", np.nan, inplace = True)

df_test.Credit_Amount = pd.to_numeric(df_test.Credit_Amount)

In [180]:
df_test.Loan_Annuity.replace(["#VALUE!","$"], np.nan, inplace = True)

df_test.Loan_Annuity = pd.to_numeric(df_test.Loan_Annuity)

In [181]:
df_test.Age_Days.replace("x", np.nan, inplace = True)

df_test.Age_Days = pd.to_numeric(df_test.Age_Days)

In [182]:
df_test.Employed_Days.replace("x", np.nan, inplace = True)

df_test.Employed_Days = pd.to_numeric(df_test.Employed_Days)

In [183]:
df_test.Registration_Days.replace("x", np.nan, inplace = True)

df_test.Registration_Days = pd.to_numeric(df_test.Registration_Days)

In [184]:
df_test.ID_Days.replace("x", np.nan, inplace = True)

df_test.ID_Days = pd.to_numeric(df_test.ID_Days)

In [185]:
df_test["Score_Source_3"].replace("#", np.nan, inplace=True)

df_test.Score_Source_3 = pd.to_numeric(df_test.Score_Source_3)

In [186]:
df_test["Score_Source_2"].replace("#", np.nan, inplace=True)

df_test.Score_Source_2 = pd.to_numeric(df_test.Score_Source_2)

In [187]:
# FEATURE ENGINEERING

# NEW COLUMN IS CREATED ON THE BASIS OF POPULATION REGION RELATIVE COLUMN WHETHER THE CLIENT AREA IS POPULATED AREA OR NOT

df_test["Population_Region_Relative"].replace(["#","@"], np.nan, inplace=True)

df_test.Population_Region_Relative = pd.to_numeric(df_test.Population_Region_Relative)

populated_Region_mean = df_test.Population_Region_Relative.mean()

temp = df_test.copy()

temp[temp["Population_Region_Relative"] < populated_Region_mean] = 0 # 0 for less populated area

temp[temp["Population_Region_Relative"] >= populated_Region_mean] = 1 # 1 for high populated area

df_test["Population_Region_Relative"] = temp["Population_Region_Relative"]

In [188]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80900 entries, 0 to 80899
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   ID                          80900 non-null  int64  
 1   Client_Income               78449 non-null  float64
 2   Car_Owned                   78495 non-null  float64
 3   Bike_Owned                  78414 non-null  float64
 4   Active_Loan                 78446 non-null  float64
 5   House_Own                   78553 non-null  float64
 6   Child_Count                 78572 non-null  float64
 7   Credit_Amount               78609 non-null  float64
 8   Loan_Annuity                77692 non-null  float64
 9   Accompany_Client            79692 non-null  object 
 10  Client_Income_Type          78399 non-null  object 
 11  Client_Education            78550 non-null  object 
 12  Client_Marital_Status       78457 non-null  object 
 13  Client_Gender               792

In [189]:
# DROPPING ID COLUMN

df_test.drop('ID', axis = 1,inplace=True)

df_test.tail(2)

Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  \
80898        13500.0        0.0         0.0          1.0        0.0   
80899        10350.0        1.0         0.0          0.0        0.0   

       Child_Count  Credit_Amount  Loan_Annuity Accompany_Client  \
80898          0.0        25470.0       1435.05            Alone   
80899          1.0        26955.0       1475.10            Alone   

      Client_Income_Type  ... Cleint_City_Rating Application_Process_Day  \
80898            Service  ...                2.0                     6.0   
80899                NaN  ...                3.0                     4.0   

      Application_Process_Hour Client_Permanent_Match_Tag  \
80898                      5.0                        Yes   
80899                      9.0                        Yes   

      Client_Contact_Work_Tag       Type_Organization  Score_Source_2  \
80898                     Yes        Industry: type 9        0.236402   
80899                     Yes  Business Entity Type 2        0.442904   

       Score_Source_3  Phone_Change  Credit_Bureau  
80898        0.579727        1186.0            2.0  
80899        0.456110        1056.0            1.0  

[2 rows x 35 columns]

In [190]:
df_test.isna().sum()

Client_Income                  2451
Car_Owned                      2405
Bike_Owned                     2486
Active_Loan                    2454
House_Own                      2347
Child_Count                    2328
Credit_Amount                  2291
Loan_Annuity                   3208
Accompany_Client               1208
Client_Income_Type             2501
Client_Education               2350
Client_Marital_Status          2443
Client_Gender                  1627
Loan_Contract_Type             2321
Client_Housing_Type            2408
Population_Region_Relative     3278
Age_Days                       2484
Employed_Days                  2426
Registration_Days              2403
ID_Days                        3886
Mobile_Tag                        0
Homephone_Tag                     0
Workphone_Working                 0
Client_Occupation             27845
Client_Family_Members          1644
Cleint_City_Rating             1631
Application_Process_Day        1539
Application_Process_Hour    

In [191]:
# APPLYING MODE

df_test.iloc[:, 0 : 5] = si_mode.fit_transform(df_test.iloc[:, 0 : 5])

df_test.iloc[:, 8 : 16] = si_mode.fit_transform(df_test.iloc[:, 8 : 16])

df_test.iloc[:, 20 : 31] = si_mode.fit_transform(df_test.iloc[:, 20 : 31])

df_test.iloc[:, 34 : 35] = si_mode.fit_transform(df_test.iloc[:, 34 : 35])

In [192]:
# APPLYING MEAN

df_test.iloc[:, 6 : 8] = si_mean.fit_transform(df_test.iloc[:, 6 : 8])

df_test.iloc[:, 31 : 34] = si_mean.fit_transform(df_test.iloc[:, 31 : 34])

In [193]:
# APPLYING MEAN WITH ROUND FUNCTION FOR REQ COLUMNS

df_test.iloc[:, 5 : 6] = np.round(si_mean.fit_transform(df_test.iloc[:, 5 : 6]))

df_test.iloc[:, 16 : 20] = np.round(si_mean.fit_transform(df_test.iloc[:, 16 : 20]))

In [194]:
df_test.isna().sum()

Client_Income                 0
Car_Owned                     0
Bike_Owned                    0
Active_Loan                   0
House_Own                     0
Child_Count                   0
Credit_Amount                 0
Loan_Annuity                  0
Accompany_Client              0
Client_Income_Type            0
Client_Education              0
Client_Marital_Status         0
Client_Gender                 0
Loan_Contract_Type            0
Client_Housing_Type           0
Population_Region_Relative    0
Age_Days                      0
Employed_Days                 0
Registration_Days             0
ID_Days                       0
Mobile_Tag                    0
Homephone_Tag                 0
Workphone_Working             0
Client_Occupation             0
Client_Family_Members         0
Cleint_City_Rating            0
Application_Process_Day       0
Application_Process_Hour      0
Client_Permanent_Match_Tag    0
Client_Contact_Work_Tag       0
Type_Organization             0
Score_So

In [195]:
from sklearn.preprocessing import LabelEncoder

cols = ["Accompany_Client","Client_Income_Type", "Client_Marital_Status", "Client_Education", "Client_Gender", "Loan_Contract_Type", "Client_Housing_Type", "Client_Occupation", "Client_Permanent_Match_Tag", "Client_Contact_Work_Tag", "Type_Organization"]
test_final[cols] = test_final[cols].apply(LabelEncoder().fit_transform)

In [196]:
df_test.to_csv("Vehicle_Loan_Test_Data.csv",index=False)

In [197]:
test_final=pd.read_csv(r"C:\Users\HP\SPJP\Vehicle_Loan_Test_Data.csv")

test_final.head()

Client_Income  Car_Owned  Bike_Owned  Active_Loan  House_Own  Child_Count  \
0        11250.0        0.0         1.0          1.0        1.0          0.0   
1        13500.0        1.0         1.0          1.0        1.0          3.0   
2        38250.0        0.0         1.0          0.0        1.0          0.0   
3        20250.0        0.0         0.0          1.0        0.0          0.0   
4        13500.0        1.0         1.0          0.0        1.0          0.0   

   Credit_Amount  Loan_Annuity Accompany_Client Client_Income_Type  ...  \
0      112500.00       4474.80         Relative            Service  ...   
1       49752.00       3252.15            Alone            Service  ...   
2       67500.00       3375.00            Alone         Commercial  ...   
3       50849.55       3814.65            Alone           Govt Job  ...   
4       43603.20       2515.95            Alone            Service  ...   

  Cleint_City_Rating Application_Process_Day Application_Process_Hour  \
0                2.0                     4.0                     16.0   
1                3.0                     3.0                     18.0   
2                1.0                     2.0                     19.0   
3                2.0                     6.0                     20.0   
4                2.0                     1.0                     13.0   

  Client_Permanent_Match_Tag Client_Contact_Work_Tag       Type_Organization  \
0                        Yes                     Yes           Self-employed   
1                         No                     Yes           Self-employed   
2                        Yes                     Yes  Business Entity Type 3   
3                         No                      No                Medicine   
4                        Yes                     Yes           Self-employed   

   Score_Source_2  Score_Source_3  Phone_Change  Credit_Bureau  
0        0.757151        0.629674         716.0            2.0  
1        0.342269        0.511575         181.0            0.0  
2        0.683665        0.511575         281.0            0.0  
3        0.229950        0.672243        1442.0            4.0  
4        0.566971        0.730987         927.0            1.0  

[5 rows x 35 columns]

In [211]:
user_input=pd.DataFrame({
                 'Client_Income':11250,
                 'Car_Owned':0,
                 'Bike_Owned':1,
                 'Active_Loan':1,
                 'House_Own':1,
                 'Child_Count':0,
                 'Credit_Amount':112500,
                'Loan_Annuity':4474.8,
                'Accompany_Client':6,
                'Client_Income_Type':4,
                'Client_Education':3,
                'Client_Marital_Status':1,
                'Client_Gender':1,
                'Loan_Contract_Type':0,
                'Client_Housing_Type':1,
                'Population_Region_Relative':0,
                'Age_Days':20063,
                'Employed_Days':2523,
                'Registration_Days':2318,
                'ID_Days':3318,
                'Mobile_Tag':1,
                'Homephone_Tag':0,
                'Workphone_Working':0,
                'Client_Occupation':8,
                'Client_Family_Members':2,
                'Cleint_City_Rating':2,
                'Application_Process_Day':4,
               'Application_Process_Hour':16,
                'Client_Permanent_Match_Tag':1,
                'Client_Contact_Work_Tag':1,
                'Type_Organization':42,
                'Score_Source_2':0.757151,
                'Score_Source_3':0.629674,
                'Phone_Change':716,
                'Credit_Bureau':2},index=[0])


y_p=class_model_afhp.predict(user_input)
if(y_p==0):
  print("No Default")
else:
  print("default" )

No Default


In [212]:
user_input=pd.DataFrame({
                 'Client_Income':13500,
                 'Car_Owned':0,
                 'Bike_Owned':0,
                 'Active_Loan':0,
                 'House_Own':1,
                 'Child_Count':0,
                 'Credit_Amount':90000,
                'Loan_Annuity':2413.35,
                'Accompany_Client':1,
                'Client_Income_Type':4,
                'Client_Education':4,
                'Client_Marital_Status':3,
                'Client_Gender':1,
                'Loan_Contract_Type':0,
                'Client_Housing_Type':1,
                'Population_Region_Relative':1,
                'Age_Days':23322,
                'Employed_Days':365423,
                'Registration_Days':211,
                'ID_Days':5255,
                'Mobile_Tag':1,
                'Homephone_Tag':0,
                'Workphone_Working':1,
                'Client_Occupation':8,
                'Client_Family_Members':1,
                'Cleint_City_Rating':1,
                'Application_Process_Day':2,
               'Application_Process_Hour':13,
                'Client_Permanent_Match_Tag':1,
                'Client_Contact_Work_Tag':1,
                'Type_Organization':57,
                'Score_Source_2':0.601859,
                'Score_Source_3':0.4171,
                'Phone_Change':1412,
                'Credit_Bureau':2},index=[0])


In [213]:
y_p=class_model_afhp.predict(user_input)
if(y_p==1):
    print("default")
else:
    print("no default")

default
